[package]
name = "OpenTanktrouble"
version = "0.1.0"
authors = ["Tnze <cjd001113@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.19"
vulkano-win = "0.19"
vulkano-shaders = "0.19.0"
winit = "0.22"

png = "0.15.0"
cgmath = "0.17"